/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */


plugins {
	application
	
    `java-library`
    `java-library-distribution`
    
     id("org.openjfx.javafxplugin") version "0.0.8"
}

repositories {
    mavenCentral()
}

dependencies {
	implementation("org.apache.logging.log4j:log4j-core:2.13.0")
	implementation("org.apache.logging.log4j:log4j-jcl:2.13.0")

	implementation("com.beust:jcommander:1.78")
}

javafx {
    version = "11"
    modules("javafx.controls", "javafx.fxml")
}

java {
    group = "de.acagamics"
	version = "1.2.4"

    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    
    withJavadocJar()
    withSourcesJar()
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "de.acagamics.framework.Main"
    }
}

application {
	mainClassName = "de.acagamics.framework.Main"
}
